version: "3.7"
services:
  alpine-container: 
    image: alpine
    tty: true
    stdin_open: true  
    restart: on-failure  
    networks:
      - linux_swarm
    deploy:
      replicas: 1
         


  archlinux-container:
    image: archlinux
    tty: true
    stdin_open: true
    restart: on-failure
    networks:
      - linux_swarm
    deploy:
      replicas: 1

  ubuntu-container:
    image: ubuntu
    tty: true
    stdin_open: true
    restart: on-failure
    networks: 
      - linux_swarm
    deploy:
      replicas: 1

  debian-container:
    image: debian
    tty: true
    stdin_open: true
    restart: on-failure
    networks:
      - linux_swarm
    deploy:
      replicas: 1
     
  oracle-container: 
    image: oraclelinux:9
    tty: true
    stdin_open: true
    restart: on-failure
    networks:
      - linux_swarm
    deploy:
      replicas: 1

  rockylinux-container: #gross 
    image: rockylinux:9.0
    tty: true
    stdin_open: true
    restart: on-failure
    networks:
      - linux_swarm
    deploy:
      replicas: 1

  suse-container: 
    image: opensuse/leap
    tty: true
    stdin_open: true
    restart: on-failure
    networks:
      - linux_swarm
    deploy:
      replicas: 1

  centos-container:
    image: centos
    tty: true
    stdin_open: true
    restart: on-failure
    networks:
      - linux_swarm
    deploy:
      replicas: 1

  fedora-container: 
    image: fedora
    tty: true
    stdin_open: true
    restart: on-failure
    networks:
      - linux_swarm
    deploy:
      replicas: 1

networks:
  linux_swarm:
    external: true 
